version: "3"
services:
        appen-suite-server:
                container_name: appen-suite-server
                image: "appen-suite-server/latest"
                restart: always
                build: .
                ports:
                  - "8080:8080"
                links:
                  - mongo
        mongo:
                container_name: mongo
                image: mongo
                volumes:
                  - ./data:/data/db
                ports:
                  - "27017:27017"

